language: python
python:
  - '3.9'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=seezlangues.settings.travis

script:
  - pytest
