# Generated by Django 3.1.4 on 2021-01-11 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('is_anonymous', models.BooleanField(null=True)),
                ('is_public', models.BooleanField(null=True)),
                ('ext_link', models.URLField(max_length=600, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_article_public', 'Can view public article'), ('view_anonymous_article', 'Can view writer of anonymous article'), ('add_anonymous_article', 'Can add anonymous article'), ('del_user_articles', 'Can delete its own articles'), ('del_users_articles', "Can delete other users' articles"), ('change_user_articles', 'Can change its own articles'), ('change_users_articles', "Can change other users' articles")),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('parent_category', models.ForeignKey('self', related_name='sub_category', on_delete=models.SET_NULL, null=True)),
                ('articles', models.ManyToManyField(to='app_blog.Article')),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'permissions': (('edit_category', 'Can edit a category'), ('del_category', 'Can delete a category'), ('view_category_forum', 'Can view Forum'), ('view_category_all_wo_c_f', 'Can view all category w/o Conseillers&Forum'), ('view_category_all', 'Can view all category')),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('original_content', models.TextField(null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.article')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_comment', 'Can edit a comment'), ('del_user_comment', 'Can delete its own comments'), ('del_users_comment', "Can delete other users' comments")),
            },
        ),
    ]
